export const ActionTypes = {
  FETCH_PRODUCTS: "FETCH_PRODUCTS",
  OPEN_CONFIRM_MODAL_DATA: "OPEN_CONFIRM_MODAL_DATA",
  OPEN_SUCCESS_MODAL_DATA: "OPEN_SUCCESS_MODAL_DATA",
  CLOSE_MODAL: "CLOSE_MODAL",
  GET_FAVORITES_PRODUCTS: "GET_FAVORITES_PRODUCTS",
  GET_CART_PRODUCTS: "GET_CART_PRODUCTS",
  INCREASE_CART_PRODUCTS: "INCREASE_CART_PRODUCTS",
  DECREASE_CART_PRODUCTS: "DECREASE_CART_PRODUCTS",
  REMOVE_CART_PRODUCTS: "REMOVE_CART_PRODUCTS",
};
